name: 'Hello World'
description: 'Greet someone and record the time'
branding:
  icon: 'heart'
  color: 'blue'

inputs:

  flutter_version:
    description: 'Flutter version'
    required: false
    default: '3.3.3'

  flutter_channel:
    description: 'Flutter channel'
    required: false
    default: 'stable'

  path: 
    description: 'Path to file'
    required: false
    default: 'build/app/outputs/flutter-apk/app-release.apk'

  slack_token:
    description: 'Slack token'
    required: false

  telegram_token:
    description: 'Telegram token'
    required: false

  telegram_chat_id:
    description: 'Telegram chat id'
    required: false

  channel:
    description: 'Slack channels'
    required: false

  filename: 
    description: 'Filename of file'
    required: false
    default: 'pinky.apk'
    
  filetype:
    description: 'A file type identifier.'
    required: false
    default: 'apk'

  comment:
    description: 'The message text introducing the file in specified channels.'
    required: false
    default: 'New build'

  webhook_url:
    description: 'The webhook url to send the message to.'
    required: false
    


runs:
  using: "composite"
  steps:  
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{inputs.flutter_version}}
        channel: ${{inputs.flutter_channel}}
    - run: flutter pub get
      shell: bash
    - run: flutter build apk 
      shell: bash

    - uses: ./src/
      id: hello
      with:
        path: ${{inputs.path}}
        slack_token: ${{inputs.slack_token}}
        telegram_token: ${{inputs.telegram_token}}
        telegram_chat_id: ${{inputs.telegram_chat_id}}
        channel: ${{inputs.channel}}
        filename: ${{inputs.filename}}
        filetype: ${{inputs.filetype}}
        comment: ${{inputs.comment}}
        webhook_url: ${{inputs.webhook_url}}

    - run: echo "The time was ${{ steps.hello.outputs.slack_result }}"
      shell: bash

