name: 'Pinky Flutter'
description: 'Flutter git action that makes you do more'
branding:
  icon: 'heart'
  color: 'blue'

inputs:

  flutter_version:
    description: 'Flutter version'
    required: false
    default: '3.3.3'

  flutter_channel:
    description: 'Flutter channel'
    required: false
    default: 'stable'

  path: 
    description: 'Path to file'
    required: false
    default: 'build/app/outputs/flutter-apk/app-release.apk'

  slack_token:
    description: 'Slack token'
    required: false

  telegram_token:
    description: 'Telegram token'
    required: false

  telegram_chat_id:
    description: 'Telegram chat id'
    required: false

  channel:
    description: 'Slack channels'
    required: false

  filename: 
    description: 'Filename of file'
    required: false
    default: 'pinky.apk'
    
  filetype:
    description: 'A file type identifier.'
    required: false
    default: 'apk'

  comment:
    description: 'The message text introducing the file in specified channels.'
    required: false
    default: 'New build'

  webhook_url:
    description: 'The webhook url to send the message to.'
    required: false
    
  usePicky:
   description: 'Indicate either you wanna use our picky bot'
   required: false

  web: 
   description: 'Deploy Flutter web with git pages'
   required: false
   default: false



runs:
  using: "composite"
  steps:  
    - name: Setting up Flutter 🦋
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{inputs.flutter_version}}
        channel: ${{inputs.flutter_channel}}
    - run: flutter pub get
      shell: bash
    
    - name: Building Flutter apk 👓
    - run: flutter build apk --profile --split-per-abi
      shell: bash

    - name: Building Flutter Web ⛑️
      # if: ${{ inputs.web }} == 'true' 
    - run: flutter build web
      shell: bash


    - name: Processing File 🛎️
      uses: rexthecoder/Pinky-Generator@1.3
      with:
        path: ${{inputs.path}}
        slack_token: ${{inputs.slack_token}}
        telegram_token: ${{inputs.telegram_token}}
        telegram_chat_id: ${{inputs.telegram_chat_id}}
        channel: ${{inputs.channel}}
        filename: ${{inputs.filename}}
        filetype: ${{inputs.filetype}}
        comment: ${{inputs.comment}}
        webhook_url: ${{inputs.webhook_url}}
        usePicky: ${{inputs.usePicky}}
    
    - name: Deploying web 🚀
      # if: ${{ inputs.web }} == 'true' 
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: /build/web


